name: 'Get Latest Release'
description: 'Get the latest release from another repository and output that for use in other actions'
branding:
  icon: 'anchor'
  color: 'orange'
inputs:
  owner:
    description: 'The Github user or organization that owns the repository'
    required: false
  repo:
    description: 'The repository name'
    required: false
  repository:
    description: 'The repository name in full'
    required: false
  excludes:
    description: 'Types of releases to exclude (e.g. pre-release)'
    required: false
  token:
    description: 'token'
    required: true
outputs:
  release:
    description: 'Latest release'
runs:
  using: 'node12'
  main: 'main.js'
